# Generated by Django 3.1.7 on 2021-05-22 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_auto_20210522_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounds', models.IntegerField(default=0)),
                ('orders', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='discound',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='totalcost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='userid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrderNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
