# Generated by Django 3.1.7 on 2021-05-22 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210522_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='serviceid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='services.servicetype'),
        ),
    ]
