# Generated by Django 3.1.7 on 2021-05-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_orders_serviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='homedelivery',
            field=models.BooleanField(default=False),
        ),
    ]
