# Generated by Django 3.1.7 on 2021-05-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_orders_servicetypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='servicetypes',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
