# Generated by Django 3.1.7 on 2021-05-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20210524_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='clothtype',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='orders',
            name='usename',
            field=models.CharField(default=None, max_length=35),
        ),
    ]
