# Generated by Django 3.1.7 on 2021-05-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20210525_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounds',
            name='orders',
            field=models.IntegerField(default=1),
        ),
    ]
