# Generated by Django 3.1.7 on 2021-05-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20210526_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounds',
            name='orders',
            field=models.IntegerField(default=0),
        ),
    ]
