# Generated by Django 3.1.7 on 2021-06-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_feedback_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
