# Generated by Django 3.1.7 on 2021-06-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20210622_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payed',
            field=models.BooleanField(),
        ),
    ]
